# Generated by Django 5.0.7 on 2024-07-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('WebSite', 'WebSite'), ('Mobile app', 'Mobile app')], max_length=10)),
                ('about', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='games-icon/default.jpg', upload_to='games-icon/')),
                ('primary_color', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
