# Generated by Django 5.0.7 on 2024-07-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='games-icon/default.jpg', upload_to='games-icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('WebSite', 'WebSite'), ('Mobile app', 'Mobile app')], max_length=10)),
                ('about', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(to='tap_to_earn.gameimage')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.AddField(
            model_name='gameimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tap_to_earn.games'),
        ),
    ]
