# Generated by Django 5.0.7 on 2024-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_coin_current_price_alter_coin_market_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
