# Generated by Django 5.0.7 on 2024-08-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('WebSite', 'WebSite'), ('Mobile app', 'Mobile app')], max_length=10)),
                ('about', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='games/default.png', upload_to='games/')),
                ('author_of_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
